version: '3.8'
name: wallet-backend
services:
  kejiah-wallet-server:
    image: kejiah/kejiah-wallet-server:latest
    container_name: kejiah-wallet-server-container
    extra_hosts:
      - "host.docker.internal:${DOCKER_LINUX_IP}"
      #this didn't work for some reason
      # - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - postgres
      - cache
    ports:
      - '${PORT}:5000'
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:10.3
    container_name: postgres-container
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresdbdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  cache:
    image: redis:6.2-alpine
    container_name: redis-container
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_CACHE_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis-cache:/data
volumes:
  postgresdbdata:
  redis-cache:
