version: '3.8'
name: wallet-backend
services:
  kejiah-wallet-management-server:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
      - cache
    ports:
      - '${PORT}:5000'
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:10.3
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresdbdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  cache:
    image: redis:6.2-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '${REDIS_CACHE_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis-cache:/data
volumes:
  postgresdbdata:
  redis-cache: